// SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
// Copyright 2019 free5GC.org
//
// SPDX-License-Identifier: Apache-2.0

/*
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"fmt"
	"os"

	"github.com/urfave/cli"

	"github.com/omec-project/nrf/logger"
	nrf_service "github.com/omec-project/nrf/service"
)

var NRF = &nrf_service.NRF{}

func main() {
	app := cli.NewApp()
	app.Name = "nrf"
	logger.InitLog.Infoln(app.Name)
	app.Usage = "-free5gccfg common configuration file -nrfcfg nrf configuration file"
	app.Action = action
	app.Flags = NRF.GetCliCmd()

	if err := app.Run(os.Args); err != nil {
		logger.AppLog.Errorf("NRF Run Error: %v", err)
	}
}

func action(c *cli.Context) error {
	if err := NRF.Initialize(c); err != nil {
		logger.CfgLog.Errorf("%+v", err)
		return fmt.Errorf("failed to initialize")
	}

	NRF.Start()

	return nil
}
