// SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
// Copyright 2019 free5GC.org
//
// SPDX-License-Identifier: Apache-2.0

/*
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"context"
	"fmt"
	"os"

	"github.com/omec-project/nrf/logger"
	nrf_service "github.com/omec-project/nrf/service"
	"github.com/urfave/cli/v3"
)

var NRF = &nrf_service.NRF{}

func main() {
	app := &cli.Command{}
	app.Name = "nrf"
	logger.InitLog.Infoln(app.Name)
	app.Usage = "Network Repository Function"
	app.UsageText = "nrf -cfg <nrf_config_file.conf>"
	app.Action = action
	app.Flags = NRF.GetCliCmd()

	if err := app.Run(context.Background(), os.Args); err != nil {
		logger.AppLog.Fatalf("NRF run error: %v", err)
	}
}

func action(ctx context.Context, c *cli.Command) error {
	if err := NRF.Initialize(c); err != nil {
		logger.CfgLog.Errorf("%+v", err)
		return fmt.Errorf("failed to initialize")
	}

	NRF.Start()

	return nil
}
