// Copyright (c) 2026 Intel Corporation
// Copyright 2019 free5GC.org
// SPDX-License-Identifier: Apache-2.0

/*
NRF NFManagement Service

NRF NFManagement Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package management

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/nrf/logger"
	"github.com/omec-project/nrf/producer"
	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/utils"
	"github.com/omec-project/util/httpwrapper"
)

// Delete /subscriptions/:subscriptionID
// Deletes a subscription
func HTTPRemoveSubscription(c *gin.Context) {
	logger.ManagementLog.Infoln("Handle Delete /subscriptions/:subscriptionID")
	req := httpwrapper.NewRequest(c.Request, nil)
	req.Params["subscriptionID"] = c.Params.ByName("subscriptionID")

	httpResponse := producer.HandleRemoveSubscriptionRequest(req)

	responseBody, err := openapi.SetBody(httpResponse.Body, "application/json")
	if err != nil {
		logger.ManagementLog.Warnln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(httpResponse.Status, "application/json", responseBody.Bytes())
	}
}

// Patch /subscriptions/:subscriptionID
// Updates a subscription
func HTTPUpdateSubscription(c *gin.Context) {
	logger.ManagementLog.Infoln("Handle Patch /subscriptions/:subscriptionID")
	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		logger.ManagementLog.Errorf("Get Request Body error: %+v", err)
		c.JSON(http.StatusInternalServerError, problemDetails)
		return
	}

	req := httpwrapper.NewRequest(c.Request, nil)
	req.Params["subscriptionID"] = c.Params.ByName("subscriptionID")
	req.Body = requestBody

	httpResponse := producer.HandleUpdateSubscriptionRequest(req)
	responseBody, err := openapi.SetBody(httpResponse.Body, "application/json")
	if err != nil {
		logger.ManagementLog.Warnln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(httpResponse.Status, "application/json", responseBody.Bytes())
	}
}
