// Copyright (c) 2026 Intel Corporation
// Copyright 2019 free5GC.org
// SPDX-License-Identifier: Apache-2.0

/*
NRF NFManagement Service

NRF NFManagement Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package management

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/nrf/logger"
	"github.com/omec-project/nrf/producer"
	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/models"
	"github.com/omec-project/openapi/v2/utils"
	"github.com/omec-project/util/httpwrapper"
)

// Delete /nf-instances/:nfInstanceID
// Deregisters a given NF Instance
func HTTPDeregisterNFInstance(c *gin.Context) {
	logger.ManagementLog.Infoln("Handle Delete /nf-instances/:nfInstanceID")
	req := httpwrapper.NewRequest(c.Request, nil)
	req.Params["nfInstanceID"] = c.Params.ByName("nfInstanceID")

	httpResponse := producer.HandleNFDeregisterRequest(req)

	responseBody, err := openapi.SetBody(httpResponse.Body, "application/json")
	if err != nil {
		logger.ManagementLog.Warnln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(httpResponse.Status, "application/json", responseBody.Bytes())
	}
}

// Get /nf-instances/:nfInstanceID
// Read the profile of a given NF Instance
func HTTPGetNFInstance(c *gin.Context) {
	logger.ManagementLog.Infoln("Handle Get /nf-instances/:nfInstanceID")
	req := httpwrapper.NewRequest(c.Request, nil)
	req.Params["nfInstanceID"] = c.Params.ByName("nfInstanceID")

	httpResponse := producer.HandleGetNFInstanceRequest(req)

	responseBody, err := openapi.SetBody(httpResponse.Body, "application/json")
	if err != nil {
		logger.ManagementLog.Warnln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(httpResponse.Status, "application/json", responseBody.Bytes())
	}
}

// Put /nf-instances/:nfInstanceID
// Register a new NF Instance
func HTTPRegisterNFInstance(c *gin.Context) {
	logger.ManagementLog.Infoln("Handle Put /nf-instances/:nfInstanceID")

	var nfprofile models.NFProfile

	// step 1: retrieve http request body
	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		logger.ManagementLog.Errorf("Get Request Body error: %+v", err)
		c.JSON(http.StatusInternalServerError, problemDetails)
		return
	}

	// step 2: convert requestBody to openapi models
	err = openapi.Decode(&nfprofile, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.ManagementLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	// step 3: encapsulate the request by httpwrapper package
	req := httpwrapper.NewRequest(c.Request, nfprofile)

	// step 4: call producer
	httpResponse := producer.HandleNFRegisterRequest(req)

	for key, val := range httpResponse.Header {
		c.Header(key, val[0])
	}

	responseBody, err := openapi.SetBody(httpResponse.Body, "application/json")
	if err != nil {
		logger.ManagementLog.Warnln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(httpResponse.Status, "application/json", responseBody.Bytes())
	}
}

// Patch /nf-instances/:nfInstanceID
// Update NF Instance profile
func HTTPUpdateNFInstance(c *gin.Context) {
	logger.ManagementLog.Infoln("Handle Patch /nf-instances/:nfInstanceID")
	// step 1: retrieve http request body
	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		logger.ManagementLog.Errorf("Get Request Body error: %+v", err)
		c.JSON(http.StatusInternalServerError, problemDetails)
		return
	}

	req := httpwrapper.NewRequest(c.Request, nil)
	req.Params["nfInstanceID"] = c.Params.ByName("nfInstanceID")
	req.Body = requestBody

	httpResponse := producer.HandleUpdateNFInstanceRequest(req)

	responseBody, err := openapi.SetBody(httpResponse.Body, "application/json")
	if err != nil {
		logger.ManagementLog.Warnln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(httpResponse.Status, "application/json", responseBody.Bytes())
	}
}
