// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
NRF NFManagement Service

NRF NFManagement Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package management

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/nrf/logger"
)

// Post /:$request.body#/nfStatusNotificationUri
func HTTPOnNFStatusEventPost(c *gin.Context) {
	detail := "Handle Post /:$request.body#/nfStatusNotificationUri is not implemented"
	logger.ManagementLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
