// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
NRF NFManagement Service

NRF NFManagement Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package management

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/nrf/logger"
)

// Delete /shared-data/:sharedDataId
// Delete Shared Data identified by a given sharedDataId
func HTTPDeleteSharedData(c *gin.Context) {
	detail := "Handle Delete /shared-data/:sharedDataId is not implemented"
	logger.ManagementLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Get /shared-data/:sharedDataId
// Read the shared data identified by a given NF sharedDataId
func HTTPGetSharedData(c *gin.Context) {
	detail := "Handle Get /shared-data/:sharedDataId is not implemented"
	logger.ManagementLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Put /shared-data/:sharedDataId
// Register new Shared Data
func HTTPRegisterSharedData(c *gin.Context) {
	detail := "Handle Put /shared-data/:sharedDataId is not implemented"
	logger.ManagementLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}

// Patch /shared-data/:sharedDataId
// Update Shared Data
func HTTPUpdateSharedData(c *gin.Context) {
	detail := "Handle Patch /shared-data/:sharedDataId is not implemented"
	logger.ManagementLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
