// Copyright (c) 2026 Intel Corporation
// Copyright 2019 free5GC.org
// SPDX-License-Identifier: Apache-2.0

/*
NRF NFManagement Service

NRF NFManagement Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package management

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/nrf/logger"
	"github.com/omec-project/nrf/producer"
	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/utils"
	"github.com/omec-project/util/httpwrapper"
)

// Get /nf-instances
// Retrieves a collection of NF Instances
func HTTPGetNFInstances(c *gin.Context) {
	logger.ManagementLog.Infoln("Handle Get /nf-instances")
	req := httpwrapper.NewRequest(c.Request, nil)
	req.Query = c.Request.URL.Query()

	httpResponse := producer.HandleGetNFInstancesRequest(req)

	responseBody, err := openapi.SetBody(httpResponse.Body, "application/json")
	if err != nil {
		logger.ManagementLog.Warnln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(httpResponse.Status, "application/json", responseBody.Bytes())
	}
}

// Options /nf-instances
// Discover communication options supported by NRF for NF Instances
func HTTPOptionsNFInstances(c *gin.Context) {
	detail := "Handle Options /nf-instances is not implemented"
	logger.ManagementLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
