// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
NRF NFDiscovery Service

NRF NFDiscovery Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package discovery

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/nrf/logger"
)

// Post /:$request.body#/callbackUri
func HTTPOnScpDomainRoutingInformationChangePost(c *gin.Context) {
	detail := "Handle Post /:$request.body#/callbackUri is not implemented"
	logger.DiscoveryLog.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
