// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
NRF NFDiscovery Service

NRF NFDiscovery Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package discovery

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/nrf/logger"
)

// Get /scp-domain-routing-info
func HTTPSCPDomainRoutingInfoGet(c *gin.Context) {
	logger.DiscoveryLog.Warnln("Handle Get /scp-domain-routing-info is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}
