// Copyright (c) 2026 Intel Corporation
// SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
// Copyright 2019 free5GC.org
// SPDX-License-Identifier: Apache-2.0

/*
NRF NFDiscovery Service

NRF NFDiscovery Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.7

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package discovery

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/nrf/logger"
	"github.com/omec-project/nrf/producer"
	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/utils"
	"github.com/omec-project/util/httpwrapper"
)

// Get /nf-instances
// Search a collection of NF Instances
func HTTPSearchNFInstances(c *gin.Context) {
	logger.DiscoveryLog.Infoln("Handle Get /nf-instances")
	req := httpwrapper.NewRequest(c.Request, nil)
	req.Query = c.Request.URL.Query()
	httpResponse := producer.HandleNFDiscoveryRequest(req)

	responseBody, err := openapi.SetBody(httpResponse.Body, "application/json")
	if err != nil {
		logger.DiscoveryLog.Warnln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(httpResponse.Status, "application/json", responseBody.Bytes())
	}
}
