# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Canonical Ltd.
# Copyright 2023 Intel Corporation

name: Unit tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-test-nrf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Unit tests
        run: go test

      - name: Build
        run: go build
